#!/bin/bash

# extract_block will get the block contents between a tag.
# It accepts two arguments; the first being the function name, the sectond being the start index of the block.
# It will return the contents between the block tags.
extract_block() {
  local match=""
  local end_index=0

  match=$(cat -)
  end_index=$(echo "${match:$2}" | grep -b -o "{{/$1}}" | tail -n 1 | cut -d':' -f1)
  echo "${match:$2:$end_index}"
}

# to_lowercase will convert a string to lowercase.
to_lowercase() {
  local input="$1"
  if [[ -z "$input" ]]; then
    echo ""
  else
    echo "$input" | tr '[:upper:]' '[:lower:]'
  fi
}
